apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: gitlab
spec:
  selector:
    app: gitlab
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 2222
      targetPort: 22
  type: ClusterIP
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-http-virtual-service
  namespace: default
spec:
  hosts:
    - "gitlab.example.net"
  gateways:
    - http-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
      - destination:
          host: gitlab-service.gitlab.svc.cluster.local
          port:
            number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: gitlab-ssh-virtual-service
  namespace: default
spec:
  hosts:
    - "services.example.net"
  gateways:
    - tcp-gateway
  tcp:
  - match:
    - port: 2222
    route:
    - destination:
        host: gitlab-service.gitlab.svc.cluster.local
        port:
          number: 22