gitlab:
  domain: "{example.com}"
  protocol: "http://"
  ssh_sub_domain: "services"
  initial_root_password: "{your-first-root-password}"
  tls_credential_name: "{your-tls-secret-name}"

  persistence:
    enabled: true
    volumeName: "data"
    accessMode: ReadWriteOnce
    size: 64Gi
    storageClass: ""

  shmVolume:
    enabled: true
    sizeLimit:

smtp:
  server: "smtp.gmail.com"
  user: "s{mtp outmail user name}"
  password: "{smtp password}"

postgresql:
  host: "postgresql.postgresql.svc.cluster.local"
  port: "5432"
  username: ""
  password: ""
  database: ""

redis:
  host: "redis.gitlab.svc.cluster.local"
  port: "6379"