apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: webService
    spec:
      initContainers:
        - name: init-gitlab-data
          image: gitlab/gitlab-ce:17.8.2-ce.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Checking if /mnt/gitlab-opt is empty..."
              if [ -z "$(ls -A /mnt/gitlab-opt)" ]; then
                echo "Empty, initializing with default content..."
                cp -a /var/opt/gitlab/* /mnt/gitlab-opt/
              else
                echo "Already initialized. Skipping copy."
              fi
          volumeMounts:
            - name: gitlab-opt
              mountPath: /mnt/gitlab-opt
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:17.8.2-ce.0
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab/gitlab.rb
              subPath: gitlab.rb
            {{- if .Values.gitlab.persistence.enabled }}
            - name: gitlab-opt
              mountPath: {{ .Values.gitlab.persistence.mountPath | default "/var/opt/gitlab" }}
            {{- end }}
            {{- if .Values.gitlab.shmVolume.enabled }}
            - name: shm
              mountPath: /dev/shm
            {{- end }}
      volumes:
        - name: gitlab-config
          configMap:
            name: gitlab-config
        {{- if .Values.gitlab.persistence.enabled }}
        - name: gitlab-opt
          persistentVolumeClaim:
            claimName: {{ .Values.gitlab.persistence.volumeName | default "gitlab-opt-claim" }}
        {{- end }}
        {{- if .Values.gitlab.shmVolume.enabled }}
        - name: shm
          emptyDir:
            medium: Memory
            {{- if .Values.gitlab.shmVolume.sizeLimit }}
            sizeLimit: {{ .Values.gitlab.shmVolume.sizeLimit }}
            {{- end }}
        {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gitlab
    tier: webService
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 2222
      targetPort: 22
  type: ClusterIP