apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-etc-pv
  labels:
    type: local-etc-gitlab
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/gitlab/etc
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-opt-pv
  labels:
    type: local-opt-gitlab
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/gitlab/opt
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-etc-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitlab
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      type: local-etc-gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-opt-claim
  namespace: {{ .Release.Namespace }}
  labels:
    app: gitlab
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local-opt-gitlab
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: webService
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:17.8.2-ce.0
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
            - name: gitlab-config
              mountPath: /etc/gitlab/gitlab.rb
              subPath: gitlab.rb
            - name: gitlab-etc
              mountPath: /etc/gitlab
            - name: gitlab-opt
              mountPath: /var/opt/gitlab
      volumes:
        - name: gitlab-config
          configMap:
            name: gitlab-config
        - name: gitlab-etc
          persistentVolumeClaim:
            claimName: gitlab-etc-claim
        - name: gitlab-opt
          persistentVolumeClaim:
            claimName: gitlab-opt-claim
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gitlab
    tier: webService
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 2222
      targetPort: 22
  type: ClusterIP