apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
        tier: webService
    spec:
      containers:
        - name: gitlab
          image: gitlab/gitlab-ce:17.8.2-ce.0
          ports:
            - containerPort: 80
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: gitlab
    tier: webService
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443
    - name: ssh
      port: 2222
      targetPort: 22
  type: ClusterIP