{{- if .Values.gitlab.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{ .Values.gitlab.persistence.volumeName | default "gitlab-opt-claim" }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - {{ .Values.gitlab.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.gitlab.persistence.size | default "256Gi" }}
  {{- if .Values.gitlab.persistence.storageClass }}
  storageClassName: {{ .Values.gitlab.persistence.storageClass }}
  {{- else }}
  storageClassName: ""
  {{- end }}
{{- end }}